# docker-compose.yml
version: '3'

services: 
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
      # args:
      #   MY_VARIABLE: ???
    image: ift6758/serving:0.0.1
    ports:
      - "5000:5000"
    environment:
      COMET_API_KEY: ${COMET_API_KEY}

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:0.0.1
    ports:
      - "5001:5001"
    environment:
      SERVING_IP: "serving"
      SERVING_PORT: 5000