FROM python:3.9

WORKDIR /code
# ARG MY_VARIABLE

# # Install codebase
ADD ./serving ./serving 
RUN pip install wheel && \ 
    pip install -r serving/requirements.txt

# # Add application
ADD ./serving/app.py ./app.py

ENV SERVING_PORT=8890
EXPOSE ${SERVING_PORT}

CMD gunicorn --bind 0.0.0.0:${SERVING_PORT} --timeout 1000 --workers 1 --threads 4 app:app